### PR TITLE
Save and restore state

### PR DESCRIPTION
**Pull request by hokaccha**
Currently, recent files are removed when window is closed. I'm sure the feature which saves files is convenient.

### CODE REVIEW

**Comment by viddo** [comment]
Hi! 
Thanks for the PR, I appreciate it! I agree that such a feature probably is convenient. However I see some issues with these changes which I would like to fix before merging:
1. I don't think adding a get/set for internals is the best way to solve this. Instead, I'd suggest to implement the [official recommendation of serialization](https://atom.io/docs/v0.187.0/behind-atom-serialization-in-atom), which also comes with the benefit of having versioned states (for future changes).
2. With the current change the recent files are overwritten from the hash, which has the side-effect that already opened files are removed from the list. Using the suggested approach above, open files should be added after the recent files object is instantiated ([just like now](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/lib/recent-files.coffee#L10-L12)). This also covers the case that opening a new directory that doesn't have a previous state gets a proper setup.
3. Some existing tests fail, so at least they should be fixed.

**Comment by hokaccha** [comment]
@viddo Thank you for your review. I will fix those issues!

**Comment by viddo** [comment]
Closing, see #7

**Comment by hokaccha** [comment]
:+1: :+1: :+1:

**Pull request closed without merging**
